COVAPP = selftest

DEPLIBS += pthread

SRCS += selftest_compdeps_cmplxt.c

SRCS += selftest_queue.c
SRCS += selftest_lfqueue.c

SRCS += selftest.c

include $(NBE_DIR)/ndr.debug.mk
include $(NBE_DIR)/ndr.covapp.mk